In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torch.nn as nn
import numpy as np

from made import MADE

In [29]:
import torch.nn.functional as F

In [30]:
num_in = 10
num_hidden = [24,24,24]
num_out = num_in
num_data = 100

In [31]:
#made_net = MADE(num_in, num_hidden, num_out, nn.ReLU(), True)

In [32]:
dataset = np.random.uniform(low=-1, high=1, size=(num_data, num_in))

In [33]:
data = torch.from_numpy(dataset.astype(np.float32))

In [36]:
torch.sigmoid(data)

tensor([[0.4068, 0.4268, 0.7270, 0.6524, 0.4100, 0.3425, 0.5054, 0.7055, 0.3617,
         0.6735],
        [0.5491, 0.4462, 0.6177, 0.3488, 0.2904, 0.3994, 0.5814, 0.6770, 0.5780,
         0.5689],
        [0.3306, 0.3328, 0.7222, 0.4481, 0.5605, 0.2692, 0.6838, 0.6155, 0.5025,
         0.3005],
        [0.7300, 0.4485, 0.4214, 0.4743, 0.7160, 0.5219, 0.4843, 0.3288, 0.5146,
         0.5762],
        [0.6445, 0.4633, 0.4732, 0.5279, 0.4415, 0.6920, 0.4586, 0.5837, 0.6925,
         0.4415],
        [0.3771, 0.5360, 0.3086, 0.5663, 0.5778, 0.5887, 0.2900, 0.3223, 0.4580,
         0.5222],
        [0.6477, 0.3655, 0.5034, 0.6413, 0.3629, 0.5837, 0.5215, 0.6413, 0.4419,
         0.3352],
        [0.3543, 0.3539, 0.2896, 0.5451, 0.4593, 0.7171, 0.6500, 0.3147, 0.3018,
         0.4374],
        [0.3756, 0.6234, 0.5323, 0.7013, 0.6587, 0.3589, 0.2755, 0.3184, 0.4751,
         0.4391],
        [0.7052, 0.3534, 0.4713, 0.3509, 0.3575, 0.4449, 0.5697, 0.5379, 0.4307,
         0.7089],
        [0

In [50]:
(torch.log(1+ torch.exp(data)) + torch.log(torch.zeros_like(data)+2))

tensor([[1.2153, 1.2496, 1.9915, 1.7497, 1.2208, 1.1125, 1.3971, 1.9157, 1.1421,
         1.8125],
        [1.4897, 1.2840, 1.6546, 1.1220, 1.0363, 1.2030, 1.5639, 1.8233, 1.5559,
         1.5346],
        [1.0945, 1.0979, 1.9741, 1.2875, 1.5152, 1.0068, 1.8445, 1.6489, 1.3912,
         1.0505],
        [2.0024, 1.2883, 1.2402, 1.3362, 1.9520, 1.4312, 1.3554, 1.0918, 1.4160,
         1.5516],
        [1.7275, 1.3155, 1.3341, 1.4436, 1.2756, 1.8707, 1.3068, 1.5696, 1.8723,
         1.2757],
        [1.1665, 1.4609, 1.0622, 1.5286, 1.5555, 1.5816, 1.0357, 1.0822, 1.3057,
         1.4316],
        [1.7365, 1.1481, 1.3930, 1.7184, 1.1440, 1.5695, 1.4302, 1.7184, 1.2764,
         1.1015],
        [1.1306, 1.1299, 1.0351, 1.4808, 1.3081, 1.9558, 1.7429, 1.0710, 1.0523,
         1.2684],
        [1.1642, 1.6697, 1.4531, 1.9013, 1.7681, 1.1377, 1.0154, 1.0765, 1.3376,
         1.2713],
        [1.9148, 1.1291, 1.3304, 1.1253, 1.1355, 1.2817, 1.5363, 1.4651, 1.2565,
         1.9273],
        [1

In [60]:
a = [i for i in data[0,:]]

In [62]:
b = [np.log(2) + np.log(1+np.exp(i)) for i in a]

In [63]:
b

[tensor(1.2153),
 tensor(1.2496),
 tensor(1.9915),
 tensor(1.7497),
 tensor(1.2208),
 tensor(1.1125),
 tensor(1.3971),
 tensor(1.9157),
 tensor(1.1421),
 tensor(1.8125)]

In [64]:
[np.log(1+np.exp(i)) for i in a]

[tensor(0.5222),
 tensor(0.5565),
 tensor(1.2984),
 tensor(1.0566),
 tensor(0.5276),
 tensor(0.4193),
 tensor(0.7040),
 tensor(1.2226),
 tensor(0.4490),
 tensor(1.1194)]

In [68]:
torch.log(1+ torch.exp(data[0,:])) + torch.log(torch.zeros_like(data[0,:])+2)

tensor([1.2153, 1.2496, 1.9915, 1.7497, 1.2208, 1.1125, 1.3971, 1.9157, 1.1421,
        1.8125])

In [71]:
torch.ones_like(data)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
